# Syllabus {-}

## Contact Information

* Instructor Name: Professor James B. Elsner (he/him/his)
* Instructor Location: Bellamy Building, Room 323a
* Lesson Hours: MWF 9:05-9:55 a.m.
* Student Hours: MWF 10-10:30 a.m.

Email: <jelsner@fsu.edu>

## Course description

This course is an introduction to the quantitative analysis of geographic data (data analysis for geographers). Most of the course content will be available through Canvas and through RStudio Cloud. Please open an account with RStudio Cloud at (https://rstudio.cloud). 

Please use this link https://rstudio.cloud/spaces/12733/join?access_code=NuhGFcK71GlGuzoKzAUIe1lqgcMDyOIC7UnnFtNG to join the Spatial Data Analysis workspace on RStudio Cloud.

## Expected learning outcomes

You will describe and demonstrate the principles of data science. You will do this with a grammar for manipulating data and a grammar for making graphs. The grammars are implemented in R using the syntax of tidyverse.

## Materials

* You will need access to the internet and either an iPad, laptop, or desktop computer. 
* All course materials are available through RStudio Cloud (https://rstudio.cloud/spaces/12733/projects) and archived on Canvas.
* There is no required textbook. 
* Much of the material for the course comes from the online book: R for Data Science https://r4ds.had.co.nz/
* Additional help is available online (e.g., https://tinystats.github.io/teacups-giraffes-and-statistics/index.html)

## Class meetings

- Online: synchronous, interactive, asynchronous recordings available on Canvas
- Some lectures, lots of learn-by-doing

## Grades

* Grades are determined solely by how well you do on the regularly scheduled homework/classwork assignments. 
* There are NO quizzes, tests, or exams. 
* Synchronous attendance is expected but not required. 
* Late classwork or homework assignments will not be accepted.
* Cumulative numerical averages of 90 - 100 (outstanding) are guaranteed at least an A-, 80 - 89 (good) at least a B-, and 70 - 79 (satisfactory) at least a C-, however the exact ranges for letter grades will be determined after all work is complete.

## Academic honor code

http://www.eng.fsu.edu/~peterson/fsuhc.html

## Students With Disabilities Act

Students needing academic accommodation should: (1) register with and provide documentation to the Student Disability Resource Center (https://dos.fsu.edu/sdrc/); (2) bring a letter to me indicating the need for accommodation and what type. This should be done sometime during the first week of classes.

## Diversity & Inclusiveness

Students from all diverse backgrounds and perspectives will be well-served by this course. Student learning needs be addressed both in and out of class, and that the diversity that you bring to this class will be viewed as a resource, strength and benefit. It is my intent to present materials and activities that are respectful of diversity: gender identity, sexuality, disability, age, socioeconomic status, ethnicity, race, nationality, religion, and culture. Let me know ways to improve the effectiveness of the course for you personally, or for other students or student groups.

- If you have a name and/or set of pronouns that differ from those that appear in your official FSU records, please let me know.
- If you feel your performance is being impacted by your experiences outside of class, please don't hesitate to come and talk with me. If you prefer to speak with someone outside of the course, your academic dean is an excellent resource. 
- I (like many people) am still in the process of learning about diverse perspectives/identities. If something was said in class (by anyone) that made you feel uncomfortable, please talk to me about it.

Links to my stuff:

* [Canvas](https://cas.fsu.edu/cas/login)
* [GitHub](https://github.com/jelsner/)
* [Twitter](https://twitter.com/JBElsner)
* [Research Website](http://myweb.fsu.edu/jelsner/_site/)

## Syllabus change policy

This syllabus is a guide for the course and is subject to change with advanced notice.

## Schedule (subject to change with notice)

Week | Dates                       | Topic
-----|-----------------------------|-------
1    | August 24, 26, 28           | RStudio Cloud and R
2    | August 31, September 2, 4   | Working with R
3    | September 9, 11             | Data and data frames
4    | September 14, 16, 18        | Data analysis
5    | September 21, 23, 25        | Graphical analysis
6    | September 28, 30, October 1 | Mapping
7    | October 5, 7, 9             | Bayesian data analysis
8    | October 12, 14, 16          | Regression
9    | October 19, 21, 23          | Multiple regression
10   | October 26, 28, 30          | Regression trees
11   | November 2, 4, 6            | Spatial data
12   | November 9, 13              | Spatial data analysis
13   | November 16, 18, 19         | Geographic regression
14   | November 30, December 2, 3  | Spatial autocorrelation

I will cover new material only on Mondays and Wednesdays. On Fridays you will work on your assignment which is due at 5p.

Assignment | Due Date (no later than 5 pm)
-----------|---------------
1          | August 28
2          | September 4
3          | September 11
4          | September 18
5          | September 25
6          | October 1
7          | October 9
8          | October 16
9          | October 23
10         | October 30
11         | November 6
12         | November 13
13         | November 19
14         | December 3